# Sử dụng PHP-FPM chính thức làm image gốc
FROM php:8.2-fpm

# Cài đặt các tiện ích bổ sung cần thiết
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libonig-dev \
    libzip-dev

# Cài đặt các PHP extension
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd
# Cấp quyền cho web
RUN  chown -R www-data:www-data .
RUN  chmod -R 775 .
# Cài đặt Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Tạo thư mục làm việc và cấp quyền
RUN mkdir /application && chown 1000:1000 -R /application

# Đặt thư mục làm việc
WORKDIR /application

# Copy toàn bộ mã nguồn vào thư mục làm việc
COPY . /application

# Tạo các thư mục cần thiết và cấp quyền cho thư mục storage và bootstrap/cache
RUN mkdir -p /application/storage /application/bootstrap/cache && \
    chown -R www-data:www-data /application/storage /application/bootstrap/cache

# Đặt người dùng mặc định
USER www-data


# Expose cổng 9000 và chạy PHP-FPM
EXPOSE 9000
CMD ["php-fpm"]
